# Generated by Django 4.2.1 on 2024-08-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_email_is_verified_emailconfirmationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Private User", "Private User"),
                    ("Life Coach", "Life Coach"),
                    ("Career Coach", "Career Coach"),
                    ("Wellness/Fitness Coach", "Wellness/Fitness Coach"),
                ],
                max_length=50,
            ),
        ),
    ]
