# Generated by Django 4.2.1 on 2024-08-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_emailconfirmationtoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfirmationtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
