# Generated by Django 4.2.1 on 2025-01-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("PAID", "paid"),
                            ("EXPIRED", "expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base", "base"),
                            ("premium", "premium"),
                            ("profi", "profi"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("session_url", models.URLField(blank=True, max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=500)),
                ("subscription_id", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_and_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
