# Generated by Django 4.2.1 on 2024-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent and important", "Do First"),
                    ("Important but Not Urgent", "Schedule"),
                    ("Urgent but Not Important", "Delegate"),
                    ("Neither Urgent nor Important", "Eliminate"),
                ],
                max_length=50,
            ),
        ),
    ]
