# Generated by Django 4.2.1 on 2024-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_deadline_alter_task_finish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="finish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
