# Generated by Django 4.2.1 on 2024-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
